import 'package:provider/provider.dart';
import 'package:flutter/material.dart';
class Constants {


  static Color lightColor = Colors.white;
  static Color darkColor = Color(0xFF121212).withOpacity(0.5);
  static Color primaryColor = Color(0xFF40B5E9);
  static Color greyColor =  Colors.grey.shade200;

  static var texstyle = TextStyle(

  );
  static var textFormDecoration = InputDecoration(
enabledBorder:OutlineInputBorder(
    borderRadius: BorderRadius.circular(10),

),
  errorBorder: OutlineInputBorder(
    borderRadius: BorderRadius.circular(10),
  ),


  focusedBorder: OutlineInputBorder(
  borderRadius: BorderRadius.circular(10),
  borderSide: BorderSide(color: Constants.primaryColor )
  ),

  // prefixIcon: Icon(Icons.email_outlined),
  prefixIconColor: Colors.grey,
      suffixIconColor: Colors.grey,
      hintText: 'Yourmail@mail.com',
      hintStyle: TextStyle(
  color: Colors.grey
  )
  );

  static var button =  BoxDecoration(
      color: Constants.primaryColor,
      border: Border.all(color: Constants.primaryColor),
      borderRadius: BorderRadius.circular(8)
  );


  static List<String> countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];
  static Map<String, String> countriesCode = {
    "Afghanistan" : "+93",
    "Albania" : "+355",
    "Algeria" : "+213",
    "Andorra" : "+376",
    "Angola" : "+244",
    "Argentina" : "+54",
    "Armenia" : "+374",
    "Australia" : "+61",
    "Austria" : "+43",
    "Azerbaijan" : "+994",
    "Bahrain" : "+973",
    "Bangladesh" : "+880",
    "Barbados" : "+1246",
    "Belarus" : "+375",
    "Belgium" : "+32",
    "Belize" : "+501",
    "Benin" : "+229",
    "Bhutan" : "+975",
    "Bolivia" : "+591",
    "Bosnia and Herzegovina" : "+387",
    "Botswana" : "+267",
    "Brazil" : "+55",
    "Brunei" : "+673",
    "Bulgaria" : "+359",
    "Burkina Faso" : "+226",
    "Burundi" : "+257",
    "Cambodia" : "+855",
    "Cameroon" : "+237",
    "Canada" : "+1",
    "Cape Verde" : "+238",
    "Central African Republic" : "+236",
    "Chad" : "+235",
    "Chile" : "+56",
    "China" : "+86",
    "Colombia" : "+57",
    "Comoros" : "+269",
    "Congo" : "+242",
    "Costa Rica" : "+506",
    "Croatia" : "+385",
    "Cuba" : "+53",
    "Cyprus" : "+357",
    "Czech Republic" : "+420",
    "Denmark" : "+45",
    "Djibouti" : "+253",
    "Dominica" : "+1767",
    "Dominican Republic" : "+1809",
    "Ecuador" : "+593",
    "Egypt" : "+20",
    "El Salvador" : "+503",
    "Equatorial Guinea" : "+240",
    "Eritrea" : "+291",
    "Estonia" : "+372",
    "Ethiopia" : "+251",
    "Fiji" : "+679",
    "Finland" : "+358",
    "France" : "+33",
    "Gabon" : "+241",
    "Gambia" : "+220",
    "Georgia" : "+995",
    "Germany" : "+49",
    "Ghana" : "+233",
    "Greece" : "+30",
    "Grenada" : "+1473",
    "Guatemala" : "+502",
    "Guinea" : "+224",
    "Guinea-Bissau" : "+245",
    "Guyana" : "+592",
    "Haiti" : "+509",
    "Honduras" : "+504",
    "Hungary" : "+36",
    "Iceland" : "+354",
    "India" : "+91",
    "Indonesia" : "+62",
    "Iran" : "+98",
    "Iraq" : "+964",
    "Ireland" : "+353",
    "Israel" : "+972",
    "Italy" : "+39",
    "Ivory Coast" : "+225",
    "Jamaica" : "+1876",
    "Japan" : "+81",
    "Jordan" : "+962",
    "Kazakhstan" : "+7",
    "Kenya" : "+254",
    "Kiribati" : "+686",
    "Kuwait" : "+965",
    "Kyrgyzstan" : "+996",
    "Laos" : "+856",
    "Latvia" : "+371",
    "Lebanon" : "+961",
    "Lesotho" : "+266",
    "Liberia" : "+231",
    "Libya" : "+218",
    "Liechtenstein" : "+423",
    "Lithuania" : "+370",
    "Luxembourg" : "+352",
    "Morocco" : "+212",
    "Mozambique" : "+258",
    "Myanmar" : "+95",
    "Namibia" : "+264",
    "Nauru" : "+674",
    "Nepal" : "+977",
    "Netherlands" : "+31",
    "New Zealand" : "+64",
    "Nicaragua" : "+505",
    "Niger" : "+227",
    "Nigeria" : "+234",
    "North Korea" : "+850",
    "Norway" : "+47",
    "Oman" : "+968",
    "Pakistan" : "+92",
    "Palau" : "+680",
    "Panama" : "+507",
    "Papua New Guinea" : "+675",
    "Paraguay" : "+595",
    "Peru" : "+51",
    "Philippines" : "+63",
    "Poland" : "+48",
    "Portugal" : "+351",
    "Qatar" : "+974",
    "Romania" : "+40",
    "Russia" : "+7",
    "Rwanda" : "+250",
    "Saint Kitts and Nevis" : "+1869",
    "Saint Lucia" : "+1758",
    "Saint Vincent and the Grenadines" : "+1784",
    "Samoa" : "+685",
    "San Marino" : "+378",
    "Sao Tome and Principe" : "+239",
    "Saudi Arabia" : "+966",
    "Senegal" : "+221",
    "Serbia" : "+381",
    "Seychelles" : "+248",
    "Sierra Leone" : "+232",
    "Singapore" : "+65",
    "Slovakia" : "+421",
    "Slovenia" : "+386",
    "Solomon Islands" : "+677",
    "Somalia" : "+252",
    "South Africa" : "+27",
    "South Korea" : "+82",
    "Spain" : "+34",
    "Sri Lanka" : "+94",
    "Sudan" : "+249",
    "Suriname" : "+597",
    "Swaziland" : "+268",
    "Sweden" : "+46",
    "Switzerland" : "+41",
    "Syria" : "+963",
    "Taiwan" : "+886",
    "Tajikistan" : "+992",
    "Tanzania" : "+255",
    "Thailand" : "+66",
    "Timor-Leste" : "+670",
    "Togo" : "+228",
    "Tonga" : "+676",
    "Trinidad and Tobago" : "+1868",
    "Tunisia" : "+216",
    "Turkey" : "+90",
    "Turkmenistan" : "+993",
    "Tuvalu" : "+688",
    "Uganda" : "+256",
    "Ukraine" : "+380",
    "United Arab Emirates" : "+971",
    "United Kingdom" : "+44",
    "United States" : "+1",
    "Uruguay" : "+598",
    "Uzbekistan" : "+998",
    "Vanuatu" : "+678",
    "Vatican City" : "+379",
    "Venezuela" : "+58",
    "Vietnam" : "+84",
    "Yemen" : "+967",
    "Zambia" : "+260",
    "Zimbabwe" : "+263"

  };








  //////////////////////  LOCATION SETTINGS    /////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////
 static Map<String, List<String>> statesMap = {
    "Abia": abia,
    "Adamawa": adamawaLGAs,
    "Akwa Ibom": akwaIbomLGAs ,
    "Anambra": anambraLGAs,
    "Bauchi": bauchiLGAs,
    "Bayelsa": bayelsaLGAs,
    "Benue": benueLGAs,
    "Borno": bornoLGAs,
    "Cross River": crossRiverLGAs,
    "Delta": DeltaLGAs,
    "Ebonyi": ebonyi_lgs,
    "Edo": EdoLGAs,
    "Ekiti": EkitiLGAs,
    "Enugu": EnuguLGAs,
    "FCT": abuja_ac,
    "Gombe": GombeLGAs,
    "Imo": imo_lgs,
    "Jigawa": jigawa_lgs,
    "Kaduna": kaduna_lgs,
    "Kano": kano_lgs,
    "Katsina": katsina_lgs,
    "Kebbi": kebbi_lgs,
    "Kogi": kogi_lgs,
    "Kwara": kwara_lgs,
    "Lagos": lagos,
    "Nasarawa": nasarawa_lgs,
    "Niger": niger_lgs,
    "Ogun": ogun_lgs,
    "Ondo": ondo_lgs,
    "Osun": osun_lgs,
    "Oyo": oyo_lgs,
    "Plateau": plateau_lgs,
    "Rivers": rivers_lgs,
    "Sokoto": sokoto_lgs,
    "Taraba": taraba_lgs,
    "Yobe": yobe_lgs,
    "Zamfara": zamfara_lgs
  };
 static  List<String> abia= ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma Ngwa", "Ngwa", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South"];
 static List<String> adamawaLGAs = [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Guyuk",
    "Hong",
    "Jada",
    "Lamurde",
    "Madagali",
    "Maiha",
    "Mayo-Belwa",
    "Michika",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South"
  ];
 static List<String> akwaIbomLGAs = [
   "Abak",
   "Eastern Obolo",
   "Eket",
   "Esit Eket",
   "Essien Udim",
   "Etim Ekpo",
   "Etinan",
   "Ibeno",
   "Ibesikpo Asutan",
   "Ibiono Ibom",
   "Ika",
   "Ikono",
   "Ikot Abasi",
   "Ikot Ekpene",
   "Ini",
   "Itu",
   "Mbo",
   "Mkpat Enin",
   "Nsit Atai",
   "Nsit Ibom",
   "Nsit Ubium",
   "Obot Akara",
   "Okobo",
   "Onna",
   "Oron",
   "Oruk Anam",
   "Udung Uko",
   "Ukanafun",
   "Uruan",
   "Urue-Offong/Oruko",
   "Uyo"
 ];
 static  List<String> anambraLGAs = [
    "Aguata",
    "Anambra East",
    "Anambra West",
    "Anaocha",
    "Awka North",
    "Awka South",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Ihiala",
    "Njikoka",
    "Nnewi North",
    "Nnewi South",
    "Ogbaru",
    "Onitsha North",
    "Onitsha South",
    "Orumba North",
    "Orumba South",
    "Oyi"
  ];

  // Bauchi State LGAs
  static List<String> bauchiLGAs = [
    "Alkaleri",
    "Bauchi",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas/Gadau",
    "Jama'are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Shira",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki"
  ];

// Bayelsa State LGAs
  static List<String> bayelsaLGAs = [
    "Brass",
    "Ekeremor",
    "Kolokuma/Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa"
  ];

// Benue State LGAs
  static  List<String> benueLGAs = [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Katsina-Ala",
    "Konshisha",
    "Kwande",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Ushongo",
    "Vandeikya"
  ];

// Borno State LGAs
  static List<String> bornoLGAs = [
    "Abadam",
    "Askira/Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Gwoza",
    "Hawul",
    "Jere",
    "Kaga",
    "Kala/Balge",
    "Konduga",
    "Kukawa",
    "Kwaya Kusar",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Mobbar",
    "Monguno",
    "Ngala",
    "Nganzai",
    "Shani"
  ];

// Cross River State LGAs
  static List<String> crossRiverLGAs = [
    "Abi",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwarra",
    "Biase",
    "Boki",
    "Calabar Municipal",
    "Calabar South",
    "Etung",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala"
  ];


   // Delta State
  static List<String> DeltaLGAs = [    'Aniocha North',    'Aniocha South',    'Bomadi',    'Burutu',    'Ethiope East',    'Ethiope West',    'Ika North East',    'Ika South',    'Isoko North',    'Isoko South',    'Ndokwa East',    'Ndokwa West',    'Okpe',    'Oshimili North',    'Oshimili South',    'Patani',    'Sapele',    'Udu',    'Ughelli North',    'Ughelli South',    'Ukwuani',    'Uvwie',    'Warri North',    'Warri South',    'Warri South West'  ];

  static List<String>   ebonyi_lgs = [
  'Abakaliki',
  'Afikpo North',
  'Afikpo South',
  'Ebonyi',
  'Ezza North',
  'Ezza South',
  'Ikwo',
  'Ishielu',
  'Ivo',
  'Izzi',
  'Ohaozara',
  'Ohaukwu',
  'Onicha'
  ];

  // Edo State
  static List<String> EdoLGAs= [    'Akoko-Edo',    'Egor',    'Esan Central',    'Esan North-East',    'Esan South-East',    'Esan West',    'Etsako Central',    'Etsako East',    'Etsako West',    'Igueben',    'Ikpoba-Okha',    'Orhionmwon',    'Oredo',    'Ovia North-East',    'Ovia South-West',    'Owan East',    'Owan West',    'Uhunmwonde'  ];
  // Ekiti State
  static List<String> EkitiLGAs= [    'Ado-Ekiti',    'Efon',    'Ekiti East',    'Ekiti South-West',    'Ekiti West',    'Emure',    'Gbonyin',    'Ido-Osi',    'Ijero',    'Ikere',    'Ikole',    'Ilejemeje',    'Irepodun/Ifelodun',    'Ise/Orun',    'Moba',    'Oye'  ];
  // Enugu State
  static List<String> EnuguLGAs =[    'Aninri',    'Awgu',    'Enugu East',    'Enugu North',    'Enugu South',    'Ezeagu',    'Igbo Etiti',    'Igbo Eze North',    'Igbo Eze South',    'Isi Uzo',    'Nkanu East',    'Nkanu West',    'Nsukka',    'Oji River',    'Udenu',    'Udi',    'Uzo-Uwani'  ];
  // Gombe State
  static List<String> GombeLGAs = [    'Akko',    'Balanga',    'Billiri',    'Dukku',    'Funakaye',    'Gombe',    'Kaltungo',    'Kwami',    'Nafada/Bajoga'];

  static List<String>  imo_lgs = [
  'Aboh Mbaise',
  'Ahiazu Mbaise',
  'Ehime Mbano',
  'Ezinihitte Mbaise',
  'Ideato North',
  'Ideato South',
  'Ihitte/Uboma',
  'Ikeduru',
  'Isiala Mbano',
  'Isu',
  'Mbaitoli',
  'Ngor Okpala',
  'Njaba',
  'Nkwerre',
  'Nwangele',
  'Obowo',
  'Oguta',
  'Ohaji/Egbema',
  'Okigwe',
  'Onuimo',
  'Orlu',
  'Orsu',
  'Oru East',
  'Oru West',
  'Owerri Municipal',
  'Owerri North',
  'Owerri West'
  ];
  static List<String>  jigawa_lgs = [
  'Auyo',
  'Babura',
  'Biriniwa',
  'Birnin Kudu',
  'Buji',
  'Dutse',
  'Gagarawa',
  'Garki',
  'Gumel',
  'Guri',
  'Gwaram',
  'Gwiwa',
  'Hadejia',
  'Jahun',
  'Kafin Hausa',
  'Kaugama',
  'Kazaure',
  'Kiri Kasama',
  'Kiyawa',
  'Maigatari',
  'Malam Madori',
  'Miga',
  'Ringim',
  'Roni',
  'Sule Tankarkar',
  'Taura',
  'Yankwashi'
  ];
  static List<String>  kaduna_lgs = [
  'Birnin Gwari',
  'Chikun',
  'Giwa',
  'Igabi',
  'Ikara',
  'Jaba',
  'Jema’a',
  'Kachia',
  'Kaduna North',
  'Kaduna South',
  'Kagarko',
  'Kajuru',
  'Kaura',
  'Kauru',
  'Kubau',
  'Kudan',
  'Lere',
  'Makarfi',
  'Sabon Gari',
  'Sanga',
  'Soba',
  'Zangon Kataf',
  'Zaria'
  ];

  static List<String> kano_lgs = [
  'Ajingi',
  'Albasu',
  'Bagwai',
  'Bebeji',
  'Bichi',
  'Bunkure',
  'Dala',
  'Dambatta',
  'Dawakin Kudu',
  'Dawakin Tofa',
  'Doguwa',
  'Fagge',
  'Gabasawa',
  'Garko',
  'Garun Mallam',
  'Gaya',
  'Gezawa',
  'Gwale',
  'Gwarzo',
  'Kabo',
  'Kano Municipal',
  'Karaye',
  'Kibiya',
  'Kiru',
  'Kumbotso',
  'Kunchi',
  'Kura',
  'Madobi',
  'Makoda',
  'Minjibir',
  'Nasarawa',
  'Rano',
  'Rimin'];
  static List<String> katsina_lgs = [
  'Bakori',
  'Batagarawa',
  'Batsari',
  'Baure',
  'Bindawa',
  'Charanchi',
  'Dan Musa',
  'Dandume',
  'Danja',
  'Daura',
  'Dutsi',
  'Dutsin Ma',
  'Faskari',
  'Funtua',
  'Ingawa',
  'Jibia',
  'Kafur',
  'Kaita',
  'Kankara',
  'Kankia',
  'Katsina',
  'Kurfi',
  'Kusada',
  'Mai’Adua',
  'Malumfashi',
  'Mani',
  'Mashi',
  'Matazu',
  'Musawa',
  'Rimi',
  'Sabuwa',
  'Safana',
  'Sandamu',
  'Zango'
  ];

  static List<String> kebbi_lgs = [
  'Aleiro',
  'Arewa Dandi',
  'Argungu',
  'Augie',
  'Bagudo',
  'Birnin Kebbi',
  'Bunza',
  'Dandi',
  'Fakai',
  'Gwandu',
  'Jega',
  'Kalgo',
  'Koko/Besse',
  'Maiyama',
  'Ngaski',
  'Sakaba',
  'Shanga',
  'Suru',
  'Wasagu/Danko',
  'Yauri',
  'Zuru'
  ];
  static List<String> kogi_lgs = [
  'Adavi',
  'Ajaokuta',
  'Ankpa',
  'Bassa',
  'Dekina',
  'Ibaji',
  'Idah',
  'Igalamela Odolu',
  'Ijumu',
  'Kabba/Bunu',
  'Kogi',
  'Lokoja',
  'Mopa-Muro',
  'Ofu',
  'Ogori/Magongo',
  'Okehi',
  'Okene',
  'Olamaboro',
  'Omala',
  'Yagba East',
  'Yagba West'
  ];


  static List<String>  kwara_lgs = [
  'Asa',
  'Baruten',
  'Edu',
  'Ekiti',
  'Ifelodun',
  'Ilorin East',
  'Ilorin South',
  'Ilorin West',
  'Irepodun',
  'Isin',
  'Kaiama',
  'Moro',
  'Offa',
  'Oke Ero',
  'Oyun',
  'Pategi'
  ];
  static  List<String> lagos= ["Agege", "Alimosho", "Ajeromi-Ifelodun", "Apapa", "Amuwo-Odofin", "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"];

  static  List<String>  nasarawa_lgs = [
  'Akwanga',
  'Awe',
  'Doma',
  'Karu',
  'Keana',
  'Keffi',
  'Kokona',
  'Lafia',
  'Nasarawa',
  'Nasarawa Egon',
  'Obi',
  'Toto',
  'Wamba'
  ];

  static  List<String> niger_lgs = [
  'Agaie',
  'Agwara',
  'Bida',
  'Borgu',
  'Bosso',
  'Chanchaga',
  'Edati',
  'Gbako',
  'Gurara',
  'Katcha',
  'Kontagora',
  'Lapai',
  'Lavun',
  'Magama',
  'Mariga',
  'Mashegu',
  'Mokwa',
  'Muya',
  'Pailoro',
  'Rafi',
  'Rijau',
  'Shiroro',
  'Suleja',
  'Tafa',
  'Wushishi'
  ];

  static  List<String> ogun_lgs = [
  'Abeokuta North',
  'Abeokuta South',
  'Ado-Odo/Ota',
  'Egbado North',
  'Egbado South',
  'Ewekoro',
  'Ifo',
  'Ijebu East',
  'Ijebu North',
  'Ijebu North East',
  'Ijebu Ode',
  'Ikenne',
  'Imeko Afon',
  'Ipokia',
  'Obafemi Owode',
  'Odeda',
  'Odogbolu',
  'Ogun Waterside',
  'Remo North',
  'Sagamu'
  ];
  static  List<String> ondo_lgs = [
  'Akoko North-East',
  'Akoko North-West',
  'Akoko South-East',
  'Akoko South-West',
  'Akure North',
  'Akure South',
  'Ese Odo',
  'Idanre',
  'Ifedore',
  'Ilaje',
  'Ile Oluji/Okeigbo',
  'Irele',
  'Odigbo',
  'Okitipupa',
  'Ondo East',
  'Ondo West',
  'Ose',
  'Owo'
  ];

  static  List<String> osun_lgs = [
  'Aiyedaade',
  'Aiyedire',
  'Atakunmosa East',
  'Atakunmosa West',
  'Boluwaduro',
  'Boripe',
  'Ede North',
  'Ede South',
  'Egbedore',
  'Ejigbo',
  'Ife Central',
  'Ife East',
  'Ife North',
  'Ife South',
  'Ifedayo',
  'Ifelodun',
  'Ila',
  'Ilesa East',
  'Ilesa West',
  'Irepodun',
  'Irewole',
  'Isokan',
  'Iwo',
  'Obokun',
  'Odo Otin',
  'Ola Oluwa',
  'Olorunda',
  'Oriade',
  'Orolu',
  'Osogbo'
  ];

  static  List<String> oyo_lgs = [
  'Afijio',
  'Akinyele',
  'Atiba',
  'Atigbo',
  'Egbeda',
  'Ibadan North',
  'Ibadan North-East',
  'Ibadan North-West',
  'Ibadan South-East',
  'Ibadan South-West',
  'Ibarapa Central',
  'Ibarapa East',
  'Ibarapa North',
  'Ido',
  'Irepo',
  'Iseyin',
  'Itesiwaju',
  'Iwajowa',
  'Kajola',
  'Lagelu',
  'Ogbomosho North',
  'Ogbomosho South',
  'Ogo Oluwa',
  'Olorunsogo',
  'Oluyole',
  'Ona Ara',
  'Orelope',
  'Ori Ire',
  'Oyo East',
  'Oyo West',
  'Saki East',
  'Saki West',
  'Surulere'
  ];

  static  List<String>  plateau_lgs = [
  'Barkin Ladi',
  'Bassa',
  'Bokkos',
  'Jos East',
  'Jos North',
  'Jos South',
  'Kanam',
  'Kanke',
  'Langtang North',
  'Langtang South',
  'Mangu',
  'Mikang',
  'Pankshin',
  'Qua\'an Pan',
  'Riyom',
  'Shendam',
  'Wase'
  ];

  static  List<String>  rivers_lgs = [
  'Abua/Odual',
  'Ahoada East',
  'Ahoada West',
  'Akuku-Toru',
  'Andoni',
  'Asari-Toru',
  'Bonny',
  'Degema',
  'Eleme',
  'Emohua',
  'Etche',
  'Gokana',
  'Ikwerre',
  'Khana',
  'Obio/Akpor',
  'Ogba/Egbema/Ndoni',
  'Ogu/Bolo',
  'Okrika',
  'Omumma',
  'Opobo/Nkoro',
  'Oyigbo',
  'Port Harcourt',
  'Tai'
  ];

  static  List<String>  sokoto_lgs = [
  'Binji',
  'Bodinga',
  'Dange Shuni',
  'Gada',
  'Goronyo',
  'Gudu',
  'Gawabawa',
  'Illela',
  'Isa',
  'Kebbe',
  'Kware',
  'Rabah',
  'Sabon Birni',
  'Shagari',
  'Silame',
  'Sokoto North',
  'Sokoto South',
  'Tambuwal',
  'Tangaza',
  'Tureta',
  'Wamako',
  'Wurno',
  'Yabo'
  ];
  static  List<String>  taraba_lgs = [
  'Ardo Kola',
  'Bali',
  'Donga',
  'Gashaka',
  'Gassol',
  'Ibi',
  'Jalingo',
  'Karim Lamido',
  'Kumi',
  'Lau',
  'Sardauna',
  'Takum',
  'Ussa',
  'Wukari',
  'Yorro'];
  static  List<String> yobe_lgs = [
  'Bade',
  'Bursari',
  'Damaturu',
  'Fika',
  'Fune',
  'Geidam',
  'Gujba',
  'Gulani',
  'Jakusko',
  'Karasuwa',
  'Karawa',
  'Machina',
  'Nangere',
  'Nguru',
  'Potiskum',
  'Tarmuwa',
  'Yunusari',
  'Yusufari'
  ];

  static  List<String> zamfara_lgs = [
  'Anka',
  'Bakura',
  'Birnin Magaji/Kiyaw',
  'Bukkuyum',
  'Bungudu',
  'Gummi',
  'Gusau',
  'Kaura Namoda',
  'Maradun',
  'Maru',
  'Shinkafi',
  'Talata Mafara',
  'Chafe',
  'Zurmi'
  ];

  static  List<String> abuja_ac = [
  'Abaji',
  'Abuja Municipal',
  'Bwari',
  'Gwagwalada',
  'Kuje',
  'Kwali'
  ];











}